model: gpt-5
git: true
auto-commits: true
edit-format: diff
cache-prompts: true
cache-keepalive-pings: 2
map-refresh: files
map-tokens: 1024
test-cmd: "node --test test/*.test.js"
show-diffs: true

weak-model: gpt-4.1-nano
